# -*- coding: utf-8 -*-
"""T1_Francisca_Romero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18nOSi88P2JcN2KBJwUR33FiW7mSQd0Ns
"""

import pandas as pd
import plotly.express as px


df = pd.read_csv("sobrepeso.csv")

df.rename(columns={
    'Overweight prevalence among children under 5 years of age (% weight-for-height >+2 SD), model-based estimates':
    'Overweight (%)'
}, inplace=True)

df_filtrado = df[(df["Year"] >= 2000) & (df["Year"] <= 2021)]
df_filtrado = df_filtrado.dropna(subset=['Overweight (%)', 'Code'])


fig = px.choropleth(
    df_filtrado,
    locations="Code",
    color="Overweight (%)",
    hover_name="Entity",
    animation_frame="Year",
    color_continuous_scale=px.colors.sequential.Turbo,
    range_color=(0, 30),
    title="Prevalencia de Sobrepeso en Niños menores a 5 Años (2000–2021)"
)

fig.update_layout(
    geo=dict(showframe=False, showcoastlines=False),
    coloraxis_colorbar=dict(title="Sobrepeso (%)")
)

fig.show()

#https://ourworldindata.org/grapher/children-who-are-overweight-sdgs?time=2022

import pandas as pd
import plotly.express as px

df = pd.read_csv('caries.csv')
df_filtered = df[['ParentLocation', 'Location', 'Value']].dropna()

# Filtrar top 5 y bottom 5 por continente
filtered = (
    df_filtered.groupby('ParentLocation')
    .apply(lambda g: pd.concat([g.nlargest(4, 'Value'), g.nsmallest(4, 'Value')]))
    .reset_index(drop=True)
)


fig = px.sunburst(
    filtered,
    path=['ParentLocation', 'Location'],
    values='Value',
    color='Value',
    color_continuous_scale='tealgrn',
    title='Prevalencia de caries en niños 1-9 años en el 2019, considerando los 4 paises con más caries y los con menos caries de cada continente',
    height=700
)

fig.update_layout(
    margin=dict(t=100, l=0, r=0, b=0),
    font=dict(size=14),
    title_font=dict(size=20),
    paper_bgcolor='white'
)


#https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-untreated-caries-of-deciduous-teeth-in-children-1-9-years